
server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/graphql
    username: root
    password: Shubhra@1966
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
